service: fee-interview

plugins:
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: us-east-2

functions:
  oneAnswer:
    handler: api/oneAnswer.index
    events:
      - http:
          path: answers/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  allAnswers:
    handler: api/allAnswers.index
    events:
      - http:
          path: answers
          method: get
          cors: true
  oneQuestion:
    handler: api/oneQuestion.index
    events:
      - http:
          path: questions/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  allQuestions:
    handler: api/allQuestions.index
    events:
      - http:
          path: questions
          method: get
          cors: true
  ping:
    handler: api/ping.index
    events:
      - http:
          path: ping
          method: get
          cors: true
