'use strict';

// tests for allAnswers
// Generated by serverless-jest-plugin

const mod = require('./../api/allAnswers');
const { answers } = require('../api/text.db');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, {
  handler: 'index',
});

describe('allAnswers', () => {
  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(body).toEqual(answers);
    });
  });
});
