'use strict';

// tests for allQuestions
// Generated by serverless-jest-plugin

const mod = require('./../api/allQuestions');
const { questions } = require('../api/text.db');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, {
  handler: 'index',
});

describe('allQuestions', () => {
  it('returns all of the questions', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(body).toEqual(questions);
    });
  });
});
