'use strict';

// tests for oneAnswer
// Generated by serverless-jest-plugin

const mod = require('./../api/oneAnswer');
const { answers } = require('../api/text.db');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, {
  handler: 'index',
});

describe('oneAnswer', () => {
  it('returns the correct question', () => {
    return wrapped
      .run({
        pathParameters: {
          id: 1,
        },
      })
      .then((response) => {
        const body = JSON.parse(response.body);
        const answersWithQuestionId1 = answers.filter((a) => a.questionId === 1);
        expect(body).toEqual(answersWithQuestionId1);
      });
  });

  it('returns 404 if the question cannot be found', () => {
    return wrapped
      .run({
        pathParameters: {
          id: 100,
        },
      })
      .then((response) => {
        expect(response.statusCode).toEqual(404);
      });
  });
});
