'use strict';

// tests for oneQuestion
// Generated by serverless-jest-plugin

const mod = require('./../api/oneQuestion');
const { questions } = require('../api/text.db');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, {
  handler: 'index',
});

describe('oneQuestion', () => {
  it('returns the correct question', () => {
    return wrapped
      .run({
        pathParameters: {
          id: 1,
        },
      })
      .then((response) => {
        const body = JSON.parse(response.body);
        const questionWithId1 = questions.filter((q) => q.id === 1)[0];
        expect(body).toEqual(questionWithId1);
      });
  });

  it('returns 404 if the question cannot be found', () => {
    return wrapped
      .run({
        pathParameters: {
          id: 100,
        },
      })
      .then((response) => {
        expect(response.statusCode).toEqual(404);
      });
  });
});
