'use strict';

// tests for ping
// Generated by serverless-jest-plugin

const mod = require('../api/ping');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, {
  handler: 'ping',
});

describe('ping', () => {
  it('tells us that the api works', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(body.message).toEqual('API works!');
    });
  });
});
